#### general settings
name: AI4K_TEST
use_tb_logger: true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [0,1]

#### datasets
datasets:
  train:
    name: AI4K
    mode: AI4K
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /input/EDVR-dev/codes/dataset/train_gt_wval.lmdb
    dataroot_LQ: /input/EDVR-dev/codes/dataset/train_x4_wval.lmdb
    cache_keys: meta_info.pkl

    N_frames: 5
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 2
    GT_size: 512
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5
  groups: 4
  front_RBs: 5
  back_RBs: 40
  predeblur: false
  HR_in: false
  w_TSA: True

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 50000, 50000, 50000]
  restarts: [50000, 100000, 150000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 2e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
